get: 
  tags: 
    -  Config
  summary: Mostrar Configs
  description: Mostrar Configs
  operationId: ShowConfig
  security: 
    -  Bearer Token: []
  responses: 
    200: 
      description: OK
      content:
        application/json:
          schema:
            type: string
          examples:
            response:
              value:
                {
                  "isSucess": true,
                  "code": 200,
                  "message": "Sucesso!",
                  "payload":
                    {
                      "first_name": "example",
                      "last_name": "example2",
                      "phone": "0123456789012",
                      "email": "example@example.com",
                      "chat_id": "1",
                      "date_of_birth": "31/12/2022",
                      "cpf": "123.456.789-01",
                      "rg": "12.345.678-9",
                      "gender": "Masculino/Feminino",
                      "office": "a",
                      'account_id': '1',
                      'created_at': '2050-03-23T12:34:12;045-01:00',
                      'updated_at': '2050-03-23T12:34:12;045-01:00',
                      'id': '1'
                    },
                }
    400:
      description: OK
      content:
        application/json:
          schema:
            type: string
          examples:
            response:
              value: {
                
    "isSuccess": false,
    "code": 0,
    "message": "E_UNAUTHORIZED_ACCESS: Unauthorized access"

}

post:
  tags:
    - Config
  summary: Criar Config
  description: Criar Config
  operationId: CreateConfig
  security:
    - Bearer Token: []
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: string
          examples:
            response:
              value:
                {
                  "isSucess": true,
                  "code": 200,
                  "message": "Sucesso!",
                  "payload":
                    {
                      "first_name": "example",
                      "last_name": "example2",
                      "phone": "0123456789012",
                      "email": "example@example.com",
                      "chat_id": "1",
                      "date_of_birth": "31/12/2022",
                      "cpf": "123.456.789-01",
                      "rg": "12.345.678-9",
                      "gender": "Masculino/Feminino",
                      "office": "a",
                      'account_id': '1',
                      'created_at': '2050-03-23T12:34:12;045-01:00',
                      'updated_at': '2050-03-23T12:34:12;045-01:00',
                      'id': '1'
                    },
                }
        application/xml:
          schema:
            type: string
        text/csv:
          schema:
            type: string
    "400":
      description: Unauthorized
  requestBody:
    content:
      application/json:
        schema:
          type: string
          example:
            {
              "firstName": "example",
              "lastName": "example2",
              "phone": "0123456789012",
              "email": "example@example.com",
              "chatId": "1",
              "dateOfBirth": "31/12/2022",
              "cpf": "123.456.789-01",
              "rg": "12.345.678-9",
              "gender": "Masculino/Feminino",
              "office": "a",
            }
    description: Contact body
    required: true
