put:
  parameters: 
    - name: id
      in: path
      description: ID da Config
      required: true
      schema: 
        type: integer
        format: int64
  tags:
    - Config
  summary: Atualizar Config
  description: Atualizar Config
  operationId: UpdateConfig
  security:
    - Bearer Token: []
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: string
          examples:
            response:
              value:
                
        application/xml:
          schema:
            type: string
        text/csv:
          schema:
            type: string
    "400":
      description: Unauthorized
  requestBody:
    content:
      application/json:
        schema:
          type: string
          example:
            {
              "firstName": "example",
              "lastName": "example2",
              "phone": "0123456789012",
              "email": "example@example.com",
              "chatId": "1",
              "dateOfBirth": "31/12/2022",
              "cpf": "123.456.789-01",
              "rg": "12.345.678-9",
              "gender": "Masculino/Feminino",
              "office": "a",
            }
    description: Contact body
    required: true
