get:
  tags:
    - Products
  summary: Mostrar Produtos
  description: Mostra os Produtos
  operationId: GetProducts
  security:
    - Bearer Token: []
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: string
          examples:
            response:
              value:
                {
    "isSuccess": true,
    "code": 200,
    "message": "Sucesso!",
    "payload": [
        {
            "id": 1,
            "name": "MyBestProduct",
            "description": "My product has drinkable gold, so the gold will purify your mouth!",
            "type": "product",
            "price": "299.99",
            "unit": "100.000",
            "cost": "9000000.00",
            "created_at": "2022-06-21T10:32:52.000-04:00",
            "updated_at": "2022-06-21T10:32:52.000-04:00",
            "account_id": 1
        }
    ]
}
    "400":
      description: Internal Server Error 
      content:
        application/json:
          schema:
            type: string
          examples:
            response:
              value:
                {
                  "isSuccess": false,
                  "code": 0,
                  "message": "E_UNAUTHORIZED_ACCESS: Unauthorized access"
              }
post:
  tags:
    - Products
  summary: Criar Produto
  description: Cria um Produto
  operationId: PostProduct
  security:
    - Bearer Token: []
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: string
          examples:
            response:
              value:
                {
    "isSuccess": true,
    "code": 200,
    "message": "Sucesso!",
    "payload": {
        "name": "MyBestProduct",
        "description": "My product has drinkable gold, so the gold will purify your mouth!",
        "type": "product",
        "price": 299.99,
        "unit": 100,
        "cost": 9000000,
        "account_id": 1,
        "created_at": "2022-06-21T10:32:52.010-04:00",
        "updated_at": "2022-06-21T10:32:52.010-04:00",
        "id": 1
    }
}
    "400":
      description: Internal Server Error 
      content:
        application/json:
          schema:
            type: string
          examples:
            response:
              value:
                  {
    "isSuccess": false,
    "code": 0,
    "message": "E_UNAUTHORIZED_ACCESS: Unauthorized access"
}
  requestBody:
    content:
      application/json:
        schema:
          type: string
          example:
            {
    "name": "MyBestProduct",
    "description": "My product has drinkable gold, so the gold will purify your mouth!",
    "type": "product",
    "price": 299.99,
    "unit": 100,
    "cost": 9000000
}
    description: Product Body
    required: true