put: 
  parameters: 
    - name: id
      in: path
      description: ID do Produto
      required: true
      schema: 
        type: integer
        format: int64
  tags:
    - Products
  summary: Atualizar Produto
  description: Atualiza um Produto
  operationId: UpdateProduct
  security:
    - Bearer Token: []
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: string
          examples:
            response:
              value:
                {
    "isSuccess": true,
    "code": 200,
    "message": "Sucesso!",
    "payload": {
        "id": 1,
        "name": "MySuperBestProduct",
        "description": "My product has drinkable gold, so the gold will purify your mouth!",
        "type": "product",
        "price": 300,
        "unit": "100.000",
        "cost": "9000000.00",
        "created_at": "2022-06-21T10:32:52.000-04:00",
        "updated_at": "2022-06-21T10:38:50.630-04:00",
        "account_id": 1
    }
}
    "400":
      description: Internal Server Error 
      content:
        application/json:
          schema:
            type: string
          examples:
            response:
              value:
                  {
    "isSuccess": false,
    "code": 0,
    "message": "E_UNAUTHORIZED_ACCESS: Unauthorized access"
}
  requestBody:
    content:
      application/json:
        schema:
          type: string
          example: 
            {
    "name": "MySuperBestProduct",
    "price": 300.00
}
    description: Products Body
    required: true

delete: 
  parameters: 
    - name: id
      in: path
      description: ID do Produto
      required: true
      schema: 
        type: integer
        format: int64
  tags:
    - Products
  summary: Deletar Produto
  description: Deleta um Produto
  operationId: DeleteProduct
  security:
    - Bearer Token: []
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: string
          examples:
            response:
              value: {
                "isSuccess": true,
                "code": 200,
                "message": "Sucesso!",
                "payload": null
            }
    "400":
      description: Internal Server Error 
      content:
        application/json:
          schema:
            type: string
          examples:
            response:
              value:
                  {
    "isSuccess": false,
    "code": 0,
    "message": "E_UNAUTHORIZED_ACCESS: Unauthorized access"
}